# permissions for end users to edit wordpresssites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordpresssite-editor-role
rules:
- apiGroups:
  - webapp.awes.one
  resources:
  - wordpresssites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.awes.one
  resources:
  - wordpresssites/status
  verbs:
  - get
