# permissions for end users to view wordpresssites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordpresssite-viewer-role
rules:
- apiGroups:
  - webapp.awes.one
  resources:
  - wordpresssites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.awes.one
  resources:
  - wordpresssites/status
  verbs:
  - get
